version: '3'

services:
  api:
    image: recfac:1.8
    build: ./api
    ports:
      - "6000:6000"
  web:
    image: php:7-apache
    ports:
      - "8080:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    volumes:
      - ./www:/var/www/html
